#!/bin/bash
#
#   Helper script for building, running and debugging reveal.js Docker image
#

# Build variables
build_dir="./.build"
dockerfile="Dockerfile"
tag="reveal"
port="8000"

append_mounts(){
  for content in $*; do
    path="$(realpath -e ${content})"
    mounts+=("--mount type=bind,source=${path},target=/reveal.js/${content##*/},readonly")
  done
}

# Build image
if [ "${1}" == "build" ]; then
  shift
  docker image build "${build_dir}" --file "${dockerfile}" --tag "${tag}" --rm --compress $*

# Run image
elif [ "${1}" == "run" ]; then
  shift
  mounts=
  append_mounts $*
  docker run --rm -d --init -p ${port}:8000 ${mounts[@]} reveal

# Debug image
elif [ "${1}" == "debug" ]; then
  shift
  mounts=
  append_mounts $*
  docker run --rm --init -p ${port}:8000 ${mounts[@]} -it --entrypoint="/bin/ash" reveal

# Display usage
else
  echo "Usage: reveal [COMMAND]..."
  echo "Dockerized reveal.js helper script"
  echo ""
  echo "Commands:"
  echo "  build [OPTS]    Build image. All OPTS are passed directly to"
  echo "                  docker image build"
  echo "  run [FILES]     Mount FILES to container's /reveal.js directory and"
  echo "                  serve from port 8000"
  echo "  debug [FILES]   Mount FILES to container's /reveal.js directory and"
  echo "                  initiate interactive shell session"
  echo ""
  echo "Full source: https://github.com/marceloalcocer/docker-reveal"
fi
